version: 2
models:
  - name: stg_customers
    columns:
      - name: customer_id
        data_tests: [not_null, unique]
  - name: stg_products
    columns:
      - name: product_id
        data_tests: [not_null, unique]
  - name: stg_orders
    columns:
      - name: order_id
        data_tests: [not_null, unique]
      - name: customer_id
        data_tests:
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id
  - name: stg_order_items
    columns:
      - name: order_item_id
        data_tests: [not_null, unique]

